name: Deploy Static Website

on:
  push:
    branches: [ master ]  # 當main分支有推送時觸發
  pull_request:
    branches: [ master ]  # 當有PR到main分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true