name: Deploy Static Website

on:
  push:
    branches: [ master ]  # 當main分支有推送時觸發
  pull_request:
    branches: [ master ]  # 當有PR到main分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./decorator  # 您的HTML文件所在的目錄
          publish_branch: gh-pages  # 部署的目標分支